#+TITLE: Macro Expanse

Browser (and eventually editor) for [[https://github.com/tgetgood/lemonade][lemonade]] example projects.

[[https://tgetgood.github.io/expanse/resources/public/index.html][Try it in action]]

* Overview
	Expanse is to be a collection of code examples demonstrating what is currently
	called lemonade.

	The plan is to compile the example code directly in the browser and embed an
	editor in the page. However, until that comes to pass you'll need to clone
	this repo and run figwheel locally, using your editor of choice to play with
	the code.
* Setup
** Check It Out
	 Go to the list on [[https://tgetgood.github.io/expanse/resources/public/index.html][GitHub Pages]] or [[*With%20Figwheel][using Figwheel]] and scroll through the
	 examples. Click on an example to open it fullscreen, click again to go back
	 to the index.

	 Honestly the online version doesn't do much impressive yet, you're better off
	 running it in figwheel so you can play with it properly.
** With Figwheel
	 Clone the repo and run

	 #+BEGIN_SRC sh
	 $ lein figwheel
	 #+END_SRC

	 In the project root. Open your browser to http://localhost:3449/index.html to
	 see the page.

	 The example code is in the =examples= dir at the top level. Each example is a
	 complete clojure project that will run on its own; expanse is just a browser
	 for them.

	 With the demo running change the drawing code in any of the examples it will
	 be reloaded almost instantly.

	 Tutorial to come.
** Try Your Own Examples
	 To create your own example project use the lein template

	 #+BEGIN_SRC sh
	 $ lein new lemonade NAME
	 #+END_SRC

	 Start figwheel in your new project folder and follow the instructions from
	 the previous step.
* Caveats
** Performance
	 This is still immature software. The demos here run at 60fps in chrome 61 on
	 a ~4 year old laptop. Firefox 57 runs around 40 fps. YMMV.
* License

	Copyright © 2018 Thomas Getgood

	Distributed under the Eclipse Public License either version 1.0 or (at your
	option) any later version.
